### ISSUE TITLE
Refactor as a Library

### ISSUE THREAD

**Issue by esodan** [Philip-Scott/libgtkcanvas#7]
I propose following directory/files structure:

ROOT
meson.build
src
  All library VALA files
  meson.build
demo
  Window.vala
  meson.build
data
   meson.build
   gtkcanvas.pc.in

No subdirectories in SRC and all files related to the library are there.

If you Agree, I'll continue a PR ASAP.

**Comment by Philip-Scott** [comment]
The only thing i'm not sure i agree is with the `no subdirectories in src` but other than that, and as long as meson can also build docs, then that would be great!

Really appreciate the help! Thanks :)

**Comment by Alecaddd** [comment]
This is awesome!
I agree with @Philip-Scott in maintaining the subdirectories in the `src` folder.

Is there any specific reason why you suggested to not have any subfolder?

**Comment by esodan** [comment]
Changes merged with subdirectories in src/
